package com.aummn.addressbook.action;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;


/**
 * Disposes a <code>Window</code>. Subclasses this class to define more
 * event handling.
 * <code>WindowDisposer</code> listens to the action events and releases
 * the system's windowing resources associated with the window when detecting
 * the closing of that window.
 *
 * @author James Jin
 * @version 1.0 25/07/2018
 * @since 1.0
 */
public class WindowDisposer implements ActionListener {
    
    /* a <code>Window</code> object to be disposed */
    private Window window;
    
    
    /**
     * Creates a new <code>WindowDisposer</code> object
     */
    public WindowDisposer(Window window) {
        
        this.window = window;
        
    }
    
    /**
     * Disposes a window. Invoked when an action event occurs.
     *
     * @param actionEvent a high-level event is generated by a component
     */
    public void actionPerformed(ActionEvent actionEvent) {
        
        window.setVisible(false);
        
        /* releases all of the native screen resources used by this window */
        window.dispose();
        
    }
    
}
